/** @file stef.h
* 
* @brief An automatically generated localization file. Generated by llmsger.
*/

#ifndef STEF_H
#define STEF_H
/*---------------------DEFINE LANGUAGE USED---------------------*/
#define // Define used language

/*		EN_LAN START		*/
#ifdef EN_LAN

#define GREETINGS		"Hi"
#define EXIT		"Bye, sir!"
#define EMPTYCELL		"Bye, sir!"

#endif /* EN_LAN */
/*		EN_LAN END		*/

/*		FR START		*/
#ifdef FR

#define GREETINGS		"Salut"
#define EXIT		"Au revoir"
#define EMPTYCELL		""

#endif /* FR */
/*		FR END		*/

/*		GERMAN START		*/
#ifdef GERMAN

#define GREETINGS		"Hallo"
#define EXIT		"Tschüss"
#define EMPTYCELL		""

#endif /* GERMAN */
/*		GERMAN END		*/

#endif /* STEF_H */

/*** end of file ***/
